version: '3'
services:
    webstore:
        image: egapm/microsvcapp:webstore
        build:
            context: ../Modules/webstore/
        container_name: webstore
        ports:
        - "8070:8080"
        networks:
        - testnet
        environment:
        - JAVA_OPTS="-javaagent:/opt/egbtm/eg_btm.jar"
        volumes:
        - /opt/egbtm:/opt/egbtm
        depends_on:
        - customer
        - product
        - order
        - quote
        - payment
    customer:
        image: egapm/microsvcapp:customers
        build:
            context: ../Modules/customers/
        container_name: customer 
        networks:
        - testnet
        environment:
        - JAVA_OPTS="-javaagent:/opt/egbtm/eg_btm.jar"
        volumes:
        - /opt/egbtm:/opt/egbtm
        depends_on:
        - webstoredb 
    gateway:
        image: egapm/microsvcapp:gateway
        build:
            context: ../Modules/gateway/
        container_name: gateway 
        networks:
        - testnet
    order:
        image: egapm/microsvcapp:order
        build:
            context: ../Modules/order/
        container_name: order 
        networks:
        - testnet
        environment:
        - JAVA_OPTS="-javaagent:/opt/egbtm/eg_btm.jar"
        volumes:
        - /opt/egbtm:/opt/egbtm
        depends_on:
        - webstoredb 
    payment:
        image: egapm/microsvcapp:payment
        build:
            context: ../Modules/payment/
        container_name: payment 
        networks:
        - testnet
        environment:
        - JAVA_OPTS="-javaagent:/opt/egbtm/eg_btm.jar"
        volumes:
        - /opt/egbtm:/opt/egbtm
        depends_on:
        - gateway 
    product:
        image: egapm/microsvcapp:product
        build:
            context: ../Modules/products/
        container_name: product 
        networks:
        - testnet
        environment:
        - JAVA_OPTS="-javaagent:/opt/egbtm/eg_btm.jar"
        volumes:
        - /opt/egbtm:/opt/egbtm
        depends_on:
        - webstoredb 
    quote:
        image: egapm/microsvcapp:quote
        build:
            context: ../Modules/quote/
        container_name: quote 
        networks:
        - testnet
        environment:
        - JAVA_OPTS="-javaagent:/opt/egbtm/eg_btm.jar"
        volumes:
        - /opt/egbtm:/opt/egbtm
        depends_on:
        - webstoredb 
    webstoredb:
        image: egapm/new-webstore:mysql
        restart: always
        container_name: webstoredb 
        volumes:
        - ../Modules/mysqldb:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: root
        networks:
        - testnet

networks:
  testnet:

